import type { StudyModule } from "@/types/study";

/**
 * Ziani, Bendiab, Bouzenada & Guerar (2026), "Swin-3DART: An Efficient and
 * Robust Lightweight Transformer for Video Anomaly Detection with TG-RGB+".
 * IET Image Processing 20:e70318.
 *
 * Review extraction and study module.
 *
 * Table map, for anyone checking the numbers against the PDF:
 *   T1 p5   video evasion attacks, feature coverage   T9  p15 alpha sensitivity
 *   T2 p6   related work overview                     T10 p16 ablation C1-C5
 *   T3 p11  the three datasets                        T11 p18 fusion cost
 *   T4 p13  comparison to prior work                  T12 p18 fusion + p-values
 *   T5 p13  feature-refinement modules on UCF-Crime   T13 p19 cross-dataset
 *   T6 p14  OAcc / ASR / AccUA under T-GAP            T14 p20 model comparison
 *   T7 p15  PGD and FGSM transfer                     T15 p20 latency and energy
 *   T8 p15  low-light degradation
 *
 * Unlike most papers in this library, every table here extracts as text, so
 * each figure below is quoted directly rather than read off a rendered page.
 *
 * Note on scope: this is weakly supervised video anomaly detection, not clip
 * classification, so the headline metric is a frame-level ROC AUC and is not
 * directly comparable to the clip accuracies most of the library reports.
 */
export const moduleSwin3dart: StudyModule = {
  slug: "swin-3dart",

  premise:
    "This is the most thoroughly evaluated paper in the library. Five-fold cross-validation with standard deviations, a five-step ablation, hyperparameter sensitivity, three adversarial attacks, a low-light stress test, cross-dataset transfer, significance testing, and a full FLOPs and memory accounting — nearly every gap the other seventeen papers leave open is closed here. Which makes it all the more striking that its own Table 15 measures the model at 13.9 seconds per clip while the paper describes itself as real-time seventeen times.",

  results: [
    { label: "RLVS", value: "99.00%", note: "frame-level ROC AUC; 98.94 ±0.07 under 5-fold" },
    { label: "UBI-Fights", value: "95.02%", note: "AUC, EER 0.070 — CBAM baseline's EER is lower at 0.060" },
    { label: "UCF-Crime", value: "86.15%", note: "AUC, best in T4 by 0.7 over AFM-WSVAD" },
    { label: "Inference", value: "13.99 s/clip", note: "T15, for a 32-frame clip — roughly 2.3 FPS" },
  ],

  review: {
    architecture: {
      family: "Vision Transformer",
      backbone:
        "Video Swin Transformer base (Swin-B), pre-trained on Kinetics-400, with 3D shifted-window multi-head self-attention over non-overlapping 3D patches and hierarchical patch merging between stages. 88.8 M parameters. The paper's architectural contribution, 3DART, is inserted inside each transformer block between the layer norm and the W-MSA block, and adds no parameters at all.",
      motionEncoding:
        "Two ways, one of them unusual. Structurally, the Swin blocks attend across a 3D window, so the attention itself spans frames. But the load-bearing mechanism is at the input: a temporal gradient is computed between frames and summed pixel-wise into the normalised RGB, producing TG-RGB+ — a three-channel tensor in which moving regions are brightened before the network sees anything. Motion is therefore handed to the model as appearance, which is what lets a backbone pre-trained on ordinary RGB video consume it unchanged.",
      inputs: [
        "TG-RGB+ frames: normalised RGB summed pixel-wise with a temporal gradient, kept at three channels so the Kinetics-400 pre-trained weights stay valid",
        "32-frame clips, per the cost analysis in T11 and T15",
        "During training only, a second input of adversarially perturbed TG-RGB+ frames generated by T-GAP under an ℓ∞ threat model at ε ≈ 13/255",
        "Augmentation includes colour jittering and simulated motion blur",
      ],
      fusion:
        "Early, and by summation rather than concatenation — which is the paper's most interesting empirical finding. Concatenating TG (2 channels) with RGB (3) to make a 5-channel tensor widens the first convolutional kernel and breaks compatibility with the pre-trained weights; summing keeps three channels and preserves them. T12 measures the difference and it is not marginal.",
      supervision:
        "Weakly supervised, using the multiple-instance-learning ranking loss with smoothness and sparsity terms (Eq. 8), plus a cosine-similarity adversarial loss between clean and perturbed embeddings (Eq. 9), combined as L_MIL + αL_adv with α = 0.5 (Eq. 10). Video-level labels at training time; frame-level scores at test time.",
      notes: [
        "3DART is genuinely parameter-free, and T14 confirms it: Swin-B and Swin-3DART both have exactly 88.8 M parameters. What it does is reduce what self-attention has to chew on — the key and value tensors are passed through two parallel adaptive pooling branches, one max and one average, over depth and then space, reduced by a factor r = 3/4, concatenated and projected back with a 1×1×1 convolution. Fewer tokens reach the dot product, so FLOPs and memory fall without any weights being added or removed.",
        "The two pooling branches are doing different jobs by design: max pooling keeps the strongest temporal signal, average pooling keeps the consistent one. Concatenating both before the projection is what lets the attention see peak and background together.",
        "The TG-RGB+ trick is the cheapest form of two-stream fusion in this library. V001 runs two full 3D backbones and sums their class scores; V015 runs two spiking streams and merges their feature maps. Here the motion channel is folded into the appearance channel before the network exists, at 0.11 GFLOPs, and the network is unmodified.",
        "Calling the model lightweight is relative and the paper's own T14 shows to what. At 88.8 M parameters and 282.79 GFLOPs it is smaller than TimeSformer-HR (121.4 M, 1703 G) and ViViT-L (352.1 M, 903 G), but it carries more than twice the parameters of MViT-B (36.6 M). The gain being claimed is against Swin-B specifically, which it matches on parameters and beats by 11.9% on FLOPs.",
        "The limitations section is unusually frank and names the right things: a fixed temporal-gradient interval can miss ultra-fast motion or misbehave at variable frame rates, T-GAP perturbs only the gradient channel and not RGB, and 'the overall transformer backbone remains more computationally demanding than lightweight CNNs, which could hinder deployment on highly constrained devices'.",
      ],
    },

    attention: {
      used: true,
      kinds: ["self", "spatial", "temporal"],
      mechanisms: [
        {
          name: "3D shifted-window multi-head self-attention (Video Swin Transformer)",
          placement:
            "Throughout the backbone. Attention is computed within local 3D windows spanning space and time, with the windows shifted between consecutive blocks so context crosses window boundaries. Windowing is what keeps self-attention from being quadratic in the full token count.",
          reportedEffect:
            "Measured as the C1 baseline of T10 — plain RGB into an off-the-shelf 3D Swin-B reaches 82.70% ±0.30 on UBI-Fights, 73.07% ±0.23 on UCF-Crime and 95.62% ±0.15 on RLVS. Everything the paper adds is measured against that.",
        },
        {
          name: "3DART adaptive receptive field",
          placement:
            "Inside each Swin block, between the layer norm and the W-MSA block, acting on the key and value tensors before attention is computed. Parallel adaptive max and average pooling over depth then space, reduction factor r = 3/4, concatenated and projected by a 1×1×1 convolution.",
          reportedEffect:
            "Isolated cleanly in T10 as C1 → C3, holding the RGB input fixed: +9.78 on UBI-Fights (82.70 → 92.48), +7.82 on UCF-Crime (73.07 → 80.89) and +3.02 on RLVS. T5 additionally compares it against three other feature-refinement modules on UCF-Crime, where it reaches 86.15% against AD's 81.69%, STGA's 81.02% and SGA's 80.28%.",
        },
        {
          name: "TG-RGB+ as an attention prior",
          placement:
            "Before the network, on the raw frames. Not a learned module — the paper describes the summed temporal gradient as acting 'as an attention prior, guiding the model toward motion-relevant regions without requiring weight re-initialization'.",
          reportedEffect:
            "Isolated as C1 → C2 in T10: +9.27 on UBI-Fights, +6.09 on UCF-Crime, +2.66 on RLVS, all at p < 0.001 in T12. Also collapses the fold-to-fold spread on UBI-Fights from ±0.30 to ±0.03.",
        },
      ],
      notes: [
        "Three distinct mechanisms and all three are separately ablated, which no other paper in this library manages. T10's C1–C5 ladder isolates the input modality and the architectural module independently and then together, so the interaction is visible rather than assumed.",
        "The interaction is real but sub-additive. TG-RGB+ alone adds 9.27 points on UBI-Fights and 3DART alone adds 9.78; together they add 12.26, not 19. Both are partly finding the same signal, which is what you would expect if TG-RGB+ is a hand-built attention prior and 3DART is a learned one.",
        "Strictly, TG-RGB+ is not attention: it is a fixed, hand-specified transform with no learned weights and no dependence on the model's state. The paper's own phrase for it — an attention prior — is the right one, and it belongs in the same category as V006's entropy filter rather than alongside a trained gate.",
        "No attention map is ever visualised on a real clip. Figure 1 shows TG-RGB+ frames with motion regions highlighted, which is the input transform rather than the model's attention, and there is no localisation metric anywhere.",
      ],
    },

    efficiency: {
      parameters: "88.8 M, identical to the Swin-B baseline — 3DART adds none",
      flops:
        "282.79 GFLOPs per clip for the backbone, plus 0.11 for the TG-RGB+ fusion, total 282.90 (T15). Against Swin-B's 321 G, a reduction of 11.9%.",
      modelSize:
        "4389.72 MB of inference memory against Swin-B's 4990.23 MB, a reduction of 12.0% (T14). Reported as memory footprint rather than on-disk size.",
      throughput:
        "13,932.68 ms per clip for the backbone and 58.53 ms for the TG-RGB+ fusion, totalling 13,991.21 ms — about 14 seconds for a 32-frame clip, or roughly 2.3 frames per second (T15). Energy is reported alongside: 101.80 mJ and 0.112 mJ, totalling 101.912 mJ per clip.",
      hardware:
        "The Kaggle platform, on a TPU configuration with 330 GB of memory. No TPU generation or core count is given, and it is not stated whether the T15 latency figures were taken on that TPU or elsewhere.",
      realTime: {
        status: "measured-and-refuted",
        note: "The paper describes itself as real-time seventeen times, including in the abstract, in §4.6's claim that 'the efficiency gains from 3DART enable real-time, on-device inference', and in the conclusion. Its own T15 measures the total pipeline at 13,991.21 ms per 32-frame clip. That is about 2.3 frames per second, roughly thirteen times slower than a 30 fps stream, and the figure is the paper's own — not an inference drawn against it. The efficiency argument is made entirely in FLOPs and memory, where the numbers do support an 11.9% and 12.0% improvement over Swin-B, and the wall-clock table two rows below is never reconciled with the real-time language.",
      },
      edgeDeployment: {
        status: "claimed-without-evidence",
        note: "Edge deployment is claimed throughout — 'suitable for deployment in real-time surveillance or edge computing scenarios' in the abstract, 'practical deployability in real-time, resource-constrained environments, such as edge-based surveillance systems' in §4.6. No edge or embedded device is used; the only platform named is a Kaggle TPU with 330 GB of memory, which is the opposite of resource-constrained. A model needing 4.4 GB of inference memory does not fit most edge hardware. To its credit, the limitations section concedes that the transformer backbone 'remains more computationally demanding than lightweight CNNs, which could hinder deployment on highly constrained devices' — a sentence that sits awkwardly against the rest of the paper.",
      },
      notes: [
        "The FLOPs and memory reductions check out exactly against T14: 321 → 282.79 G is 11.90%, and 4990.23 → 4389.72 MB is 12.03%. The abstract's '~12% memory and ~11.9% FLOPs' is accurate. §4.6's description of the FLOPs saving as 'an improvement of over 12%' is not — it is 11.9%.",
        "Achieving that at an unchanged parameter count is the genuinely notable result. 3DART buys the reduction by shrinking what attention operates on rather than by removing capacity, so the usual accuracy-for-size trade does not apply — and T10's C1 → C3 shows accuracy going up, not down.",
        "The TG-RGB+ fusion is properly costed rather than waved through, which is rare here. T11 times it at 1.829 ms per frame and 472.84 MB for a 32-frame clip, and compares it against the concatenation alternative at 1.941 ms and 485.46 MB. Set against the papers in this library that leave optical flow or entropy filtering entirely uncosted, this is the right standard.",
        "One preprocessing stage is excluded and the paper says so. T-GAP begins with optical flow extraction, which §4.6 states 'can be precomputed offline', so it is not in any online figure. That is defensible for a training-time attack, but it means the numbers describe inference on already-prepared input.",
        "The energy figures (101.912 mJ per clip) are reported with no measurement method, no instrument and no power model. They are the least supported numbers in an otherwise well-instrumented section.",
        "13.9 seconds per clip on a TPU is slow enough to be worth questioning as a measurement — 282.79 GFLOPs in 13.9 s is about 20 GFLOP/s, far below what any TPU delivers. Whether the figure reflects an unoptimised implementation, CPU execution or a per-clip overhead is not recoverable from the paper. It is recorded here as printed, because it is the only wall-clock number the paper provides and it is the one that contradicts the real-time claim.",
      ],
    },

    evaluation: {
      datasets: [
        {
          name: "UBI-Fights",
          role: "evaluation",
          note: "1000 videos, 300 violent and 700 non-violent, frame-level annotations, interpersonal physical confrontations (T3). The one dataset shared with V008, which makes the two directly comparable — see the protocol notes on how this paper quotes V008's result.",
        },
        {
          name: "UCF-Crime",
          role: "evaluation",
          note: "1900 real-world surveillance videos over 13 classes, 12 anomalous plus normal — robbery, assault, burglary, explosion, fighting, abuse, vandalism, road accident, shooting (T3). Video-level labels for training, frame-interval labels for testing. Severely imbalanced, and the hardest of the three by 9 points. Elsewhere in this library it appears only as a dataset named and never run.",
        },
        {
          name: "RLVS",
          role: "evaluation",
          note: "2000 videos, evenly split, real-world violent scenes, video-level labels (T3). Clips run 5–7 s, which the paper notes makes motion cues sparse — the reason it gives for concatenation collapsing on this set. The easiest of the three at 99.00% AUC.",
        },
        {
          name: "Kinetics-400",
          role: "pre-training",
          note: "The Swin-B backbone's pre-training source (T14). Preserving compatibility with these weights is the stated reason TG-RGB+ sums rather than concatenates.",
        },
      ],
      split:
        "5-fold cross-validation, with 7000 epochs per fold, training partitions shuffled and test sets held fixed across folds. The paper states this was applied 'to the ablation configurations', and T10 and T12 report mean AUC with standard deviations accordingly. What protocol produced the headline figures of §4.3.1 is not stated; those numbers (95.02, 86.15, 99.00) sit marginally above T10's cross-validated C5 (94.99 ±0.24, 85.82 ±0.20, 98.94 ±0.07), which suggests they are single-run.",
      metrics: [
        "Frame-level ROC AUC",
        "Equal error rate",
        "Original accuracy on clean data (OAcc)",
        "Attack success rate (ASR)",
        "Accuracy under attack (AccUA)",
        "Mean and standard deviation over 5 folds",
        "Shapiro–Wilk normality test, then paired t-test or Wilcoxon",
        "GFLOPs, parameters, memory, per-clip latency, energy",
      ],
      protocolNotes: [
        "The evaluation design is the most complete in this library and it is worth listing what it covers: five-fold cross-validation with standard deviations, a five-configuration ablation isolating each component, a hyperparameter sensitivity sweep, three separate adversarial attacks including two the model was not trained against, a simulated low-light stress test, a cross-dataset transfer experiment in both directions, and significance testing with the test chosen by a normality check. Almost every gap flagged across the other seventeen extractions is closed here.",
        "The ablation is genuinely clean. T10's C1 → C3 holds the input fixed and swaps the backbone; C1 → C2 holds the backbone fixed and swaps the input; C4 combines them and C5 adds adversarial training. Each of the three contributions therefore has its own number, and the interaction is visible: TG-RGB+ alone is worth +9.27 on UBI-Fights and 3DART alone +9.78, while together they give +12.26 rather than the +19 that would follow if they were independent.",
        "T-GAP's marginal contribution is the one component that barely registers. C4 → C5 moves UBI-Fights by 0.03 points and RLVS by 0.04, against fold standard deviations of ±0.35 and ±0.02. Only UCF-Crime shows a real gain, +1.24. Adversarial training is not being sold as an accuracy improvement — its purpose is the robustness in T6 and T7 — but §4.4.2 describes the C4 → C5 step as 'the final decisive separation', which two of the three datasets do not support.",
        "The fusion analysis is the most interesting empirical result in the paper. T12 shows that concatenating the temporal gradient onto RGB as extra channels does not merely underperform summation — on RLVS it collapses the model, from a 94.97% RGB baseline to 67.03%. The explanation given is that five channels break the pre-trained Swin weights' first-layer kernel, forcing the model to relearn its input representation from short clips with sparse motion. It is a clear, well-evidenced demonstration that how a motion channel is introduced matters more than whether one is.",
        "Two cells of the RGB baseline disagree between tables. T10's C1 gives RLVS 95.62% ±0.15 and T12's RGB baseline gives 94.97% ±0.49 for what should be the same configuration; the UBI-Fights and UCF-Crime cells match exactly across both tables. The paper does not note the difference, and the +2.66 gain quoted for TG-RGB+ on RLVS depends on which baseline is used.",
        "§4.3.1's numeric claims about T5 do not follow from T5. The text reports 'a relative gain of 6.06% over the next best method (AD) and an absolute improvement of 5.13%, 5.26% and 4.95% compared to SGA, STGA and BSP-style approaches'. From the table, 86.15 against AD's 81.69 is 4.46 absolute and 5.46% relative; against SGA's 80.28 it is 5.87 and against STGA's 81.02 it is 5.13 — so the figure attributed to SGA is actually the STGA gap, 5.26 and 4.95 match nothing, and BSP-style has no row in the table at all.",
        "The headline EER claim on UBI-Fights does not hold, and the losing comparison is a paper in this library. T4 reports Swin-3DART at 0.950 AUC and 0.070 EER, against ConvLSTM2D + CBAM at 0.930 and 0.060. The text says 'the swin-3DART surpasses them all, achieving 0.95 ROC AUC and 0.07 EER'. It surpasses on AUC; on EER, lower is better and the CBAM model is ahead. The paper reports both numbers and reads only one of them.",
        "That same row is worth checking in the other direction. [45] is V008 in this library, whose own tables report six architectures on UBI-Fights spanning 0.925 to 0.9523 AUC and 0.0477 to 0.0754 EER. The 0.930 quoted here is consistent with two of V008's weaker variants; the 0.060 EER matches none of the six, the nearest being 0.0661. Comparing against V008's headline VGG16 result (0.9523 AUC, 0.0477 EER) would have narrowed the AUC margin to 0.3 points and reversed the EER comparison further.",
        "Cross-dataset generalisation is tested in both directions, which almost nothing else here does, and the results are honest about the cost of transfer. Trained on UBI-Fights and tested on UCF-Crime gives 73.65% against CrimeNet's 71.72%; trained on UCF-Crime and tested on UBI-Fights gives 74.83% against a recalculated deep-MIL-ranking baseline at 70.26%. Both are 12 to 20 points below the in-domain figures, which is the realistic picture of what these models transfer.",
        "The prose describing that experiment reverses its own table. §4.5 says 'the UBI Fights dataset ... achieved an AUC of approximately 74%, while UCF-Crime ... attained an AUC of 75%', whereas T13 gives 73.65% when tested on UCF-Crime and 74.83% when tested on UBI-Fights. The two are swapped.",
        "Adversarial robustness is tested against attacks the model was not trained on, which is the check that makes such claims meaningful. T7 puts PGD at 5.0% ASR on UBI-Fights and 8.2% on UCF-Crime, and FGSM at 5.0% and 8.3%, against T-GAP's own 4.5% and 7.5%. The small advantage for T-GAP is expected since the model was trained against it, and the fact that PGD and FGSM do not do materially better is the result that matters.",
        "No precision, recall, F1 or confusion matrix appears anywhere. The metric set is AUC, EER, and the three attack-related accuracies — which is standard for weakly supervised anomaly detection, and still means the false-alarm behaviour at any chosen operating point is not recoverable. On UCF-Crime, where §4.3.1 explicitly notes that 'long stretches of normal video without anomalies lead to a plateau in the true positive rate', that gap matters most.",
        "Two smaller inconsistencies for anyone matching tables to text: §4.2 says the significance test is selected between a paired t-test and a Wilcoxon test after a Shapiro–Wilk check, while §4.4.3 reports 'independent two-sample t-tests'; and §4.3.2 states a 2.85% accuracy drop under attack on UCF-Crime, which follows from the rounded 75% in the text rather than T6's 75.48%, where the drop is 2.37.",
        "Both headline claims should be read with their protocol attached. The 95/86/99 in the abstract are frame-level ROC AUCs for weakly supervised anomaly detection, not clip classification accuracies, and are not comparable to the accuracy figures the rest of this library reports — including V008's, on the same UBI-Fights dataset.",
      ],
    },
  },

  concepts: [
    {
      id: "tg-rgb",
      title: "Add the motion into the picture instead of alongside it",
      tagline: "TG-RGB+",
      highlight: {
        label: "Concatenation on RLVS",
        value: "98.28% → 67.03%",
        note: "the same motion signal, introduced the other way",
      },
      note: [
        "Every two-stream design in this library pays for motion twice: a second backbone, a second set of weights, an optical flow field computed per frame. This paper's input trick avoids all of it. Compute a temporal gradient between frames, normalise it, and add it pixel-wise into the RGB. Moving regions come out brighter. The tensor is still three channels wide.",
        "Three channels is the entire point. A video Swin transformer pre-trained on Kinetics-400 expects three-channel input, and TG-RGB+ hands it exactly that — so the pre-trained weights remain meaningful and the motion cue rides in as if it were appearance. The paper calls the effect an attention prior: nothing is learned, but the model is steered toward moving regions before it starts.",
        "The obvious alternative is to concatenate instead — stack the two gradient channels onto the three RGB ones and let the network sort it out with a wider first-layer kernel. Table 12 runs that experiment, and the result is the sharpest thing in the paper. On RLVS, summation reaches 98.28% AUC and concatenation reaches 67.03%, against an RGB-only baseline of 94.97%. Adding the motion the wrong way is worse than not adding it at all, by nearly 28 points.",
        "The explanation offered is that five channels widen the first convolution and break the pre-trained weights, forcing the transformer to relearn its input representation. RLVS clips are 5–7 seconds with sparse motion, so there is not enough data to relearn from. On UCF-Crime concatenation also fails to beat the baseline (70.19 against 73.07); only on UBI-Fights does it help at all, and still by 3.2 points less than summation.",
        "The cost side is measured too, which is not something this library sees often. T11 times the fusion at 1.829 ms per frame and 0.1108 GFLOPs per 32-frame clip against concatenation's 1.941 ms and 0.1171 — a 6% difference in FLOPs. So summation is both better and cheaper, and the paper checked both.",
      ],
      takeaways: [
        "Temporal gradient summed into RGB, still three channels, so Kinetics-400 pre-trained weights stay valid.",
        "Concatenation collapses RLVS to 67.03% — worse than using no motion signal at all.",
        "Worth +9.27 on UBI-Fights and +6.09 on UCF-Crime over RGB alone, all at p < 0.001.",
        "It also stabilises training: the fold-to-fold spread on UBI-Fights drops from ±0.30 to ±0.03.",
      ],
      visual: {
        kind: "model-lineup",
        options: {
          hue: 230,
          mode: "outcome",
          metricLabel: "ROC AUC",
          datasetLabel: "Dataset",
          baselineId: "rgb",
          // T12, p18. Mean AUC over 5 folds with the standard deviation as the
          // whisker. Deltas run against the RGB baseline so each fusion strategy
          // reads as a gain or loss over using no motion channel at all.
          datasets: [
            {
              id: "rlvs",
              label: "RLVS",
              title: "2000 clips, 5-7 s — where concatenation collapses",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "ubi",
              label: "UBI-Fights",
              title: "1000 videos, frame-level labels",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "ucf",
              label: "UCF-Crime",
              title: "1900 surveillance videos, severely imbalanced",
              floor: 50,
              floorLabel: "chance",
            },
          ],
          models: [
            {
              id: "sum",
              label: "TG-RGB+ (summation)",
              metrics: {
                ubi: { accuracy: 91.97, accuracySd: 0.03 },
                ucf: { accuracy: 79.16, accuracySd: 0.21 },
                rlvs: { accuracy: 98.28, accuracySd: 0.1 },
              },
            },
            {
              id: "rgb",
              label: "RGB baseline (no motion channel)",
              metrics: {
                ubi: { accuracy: 82.7, accuracySd: 0.3 },
                ucf: { accuracy: 73.07, accuracySd: 0.23 },
                rlvs: { accuracy: 94.97, accuracySd: 0.49 },
              },
            },
            {
              id: "concat",
              label: "TG-RGB+ (concatenation, 5 channels)",
              metrics: {
                ubi: { accuracy: 88.77, accuracySd: 0.03 },
                ucf: { accuracy: 70.19, accuracySd: 0.09 },
                rlvs: { accuracy: 67.03, accuracySd: 0.32 },
              },
            },
          ],
        },
        caption:
          "T12, measured against the RGB baseline. Switch to RLVS and the concatenation lane falls off a cliff — same motion information, same backbone, introduced as extra channels instead of summed in. Whiskers are the standard deviation across five folds.",
      },
      pdfPage: 18,
    },

    {
      id: "3dart",
      title: "Twelve per cent less memory, and not one parameter removed",
      tagline: "3DART",
      highlight: {
        label: "Swin-B → Swin-3DART",
        value: "321 → 282.79 G",
        note: "at an identical 88.8 M parameters",
      },
      note: [
        "The usual way to make a transformer cheaper is to make it smaller — fewer layers, narrower embeddings, fewer heads — and to pay for it in accuracy. 3DART does something else. It leaves the network exactly as it is and reduces what the attention operation has to look at.",
        "It sits inside every Swin block, between the layer norm and the windowed self-attention, and acts on the key and value tensors before the dot product. The input is passed through two parallel branches: adaptive max pooling over depth and then space, and adaptive average pooling over the same, each reducing by a factor r = 3/4. The two outputs are concatenated along the channel axis and projected back to the original width by a 1×1×1 convolution.",
        "Both branches exist because they answer different questions. Max pooling keeps the strongest temporal signal — the spike of motion that marks an event. Average pooling keeps the consistent one — the background dynamics the event has to be distinguished from. Concatenating them before the projection lets the attention see peak and baseline together.",
        "The result is the cleanest efficiency claim in this library. Table 14 puts Swin-B and Swin-3DART at exactly 88.8 M parameters each, with FLOPs falling from 321 G to 282.79 G and inference memory from 4990.23 MB to 4389.72 MB — 11.9% and 12.0%. Because the projection restores the channel width and the pooling adds no weights, the module is genuinely parameter-free, and it can be dropped into an existing backbone without retraining it from scratch.",
        "Accuracy goes up rather than down. Holding the input at plain RGB and swapping only the backbone, T10's C1 → C3 gains 9.78 points on UBI-Fights, 7.82 on UCF-Crime and 3.02 on RLVS. Table 5 puts it against three other feature-refinement modules on UCF-Crime, where it reaches 86.15% against 81.69%, 81.02% and 80.28%.",
        "One caution on the word lightweight, which is in the title. This is lightweight against Swin-B and against TimeSformer-HR at 1703 GFLOPs. It is not lightweight in absolute terms: 88.8 M parameters, 282.79 GFLOPs per clip and 4.4 GB of inference memory is more than twice the parameter count of MViT-B, which sits in the same table.",
      ],
      takeaways: [
        "Parameter-free by construction: pooling adds no weights and the 1×1×1 projection restores the original width.",
        "−11.9% FLOPs and −12.0% memory against Swin-B, both verifiable from T14's own figures.",
        "Accuracy rises as cost falls — +9.78 on UBI-Fights with the input held fixed.",
        "Lightweight is relative to Swin-B. At 4.4 GB of inference memory this does not fit an edge device.",
      ],
      pdfPage: 9,
    },

    {
      id: "ablation",
      title: "Five configurations, five folds, and every component measured alone",
      tagline: "T10",
      highlight: {
        label: "TG-RGB+ and 3DART together",
        value: "+12.26",
        note: "against +9.27 and +9.78 separately — they overlap",
      },
      note: [
        "Table 10 is what an ablation should look like. Five configurations, three datasets, five-fold cross-validation, and a standard deviation on every cell. C1 is plain RGB into an off-the-shelf 3D Swin-B. C2 swaps the input for TG-RGB+ and holds the backbone. C3 swaps the backbone for Swin-3DART and holds the input. C4 does both. C5 adds adversarial training with T-GAP.",
        "Because C2 and C3 each change exactly one thing from C1, both contributions have their own number, and the interaction between them becomes visible instead of being assumed. On UBI-Fights, TG-RGB+ alone is worth 9.27 points and 3DART alone 9.78. Together they give 12.26, not 19.05.",
        "That shortfall is the most informative number in the table, and the paper does not comment on it. It says the two components are partly finding the same thing — which makes sense if TG-RGB+ is a hand-built prior that highlights motion and 3DART is a learned mechanism that would have found much of that motion anyway. They are complementary, but not independent, and the honest reading is that either one gets you most of the way.",
        "T-GAP's own contribution is small enough to question. C4 → C5 moves UBI-Fights by 0.03 points against a ±0.35 fold spread, and RLVS by 0.04 against ±0.02. Only UCF-Crime shows a real gain at +1.24. The paper describes this step as 'the final decisive separation'; on two of three datasets it is indistinguishable from noise. That is not damning — T-GAP exists for adversarial robustness, which is measured separately and does work — but the accuracy framing overstates it.",
        "The standard deviations are worth reading in their own right. They shrink as components are added: UBI-Fights goes from ±0.30 at C1 to ±0.24 at C5, and RLVS from ±0.15 to ±0.07, with C4 tightest at ±0.02. A model that is not just better on average but more consistent across folds is a stronger claim than the mean alone, and the numbers to make it are all published.",
      ],
      takeaways: [
        "Each contribution isolated by a single-variable change from a common baseline, with folds and error bars.",
        "The two main components overlap: 9.27 + 9.78 buys 12.26, not 19.",
        "T-GAP moves accuracy by 0.03 and 0.04 points on two of three datasets — inside the fold spread.",
        "Fold variance narrows as components are added, which the paper measures and does not claim.",
      ],
      visual: {
        kind: "model-lineup",
        options: {
          hue: 230,
          mode: "outcome",
          metricLabel: "ROC AUC",
          datasetLabel: "Dataset",
          baselineId: "c1",
          // T10, p16. Mean AUC over 5 folds, standard deviation as the whisker.
          // Deltas run against C1, the off-the-shelf RGB + Swin-B baseline.
          datasets: [
            {
              id: "ubi",
              label: "UBI-Fights",
              title: "the largest spread across configurations",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "ucf",
              label: "UCF-Crime",
              title: "hardest of the three by nine points",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "rlvs",
              label: "RLVS",
              title: "already at 95.62% before anything is added",
              floor: 50,
              floorLabel: "chance",
            },
          ],
          models: [
            {
              id: "c5",
              label: "C5: TG-RGB+ + Swin-3DART + T-GAP",
              metrics: {
                ubi: { accuracy: 94.99, accuracySd: 0.24 },
                ucf: { accuracy: 85.82, accuracySd: 0.2 },
                rlvs: { accuracy: 98.94, accuracySd: 0.07 },
              },
            },
            {
              id: "c4",
              label: "C4: TG-RGB+ + Swin-3DART",
              metrics: {
                ubi: { accuracy: 94.96, accuracySd: 0.35 },
                ucf: { accuracy: 84.58, accuracySd: 0.86 },
                rlvs: { accuracy: 98.9, accuracySd: 0.02 },
              },
            },
            {
              id: "c3",
              label: "C3: RGB + Swin-3DART",
              metrics: {
                ubi: { accuracy: 92.48, accuracySd: 0.53 },
                ucf: { accuracy: 80.89, accuracySd: 0.68 },
                rlvs: { accuracy: 98.64, accuracySd: 0.06 },
              },
            },
            {
              id: "c2",
              label: "C2: TG-RGB+ + Swin-B",
              metrics: {
                ubi: { accuracy: 91.97, accuracySd: 0.03 },
                ucf: { accuracy: 79.16, accuracySd: 0.21 },
                rlvs: { accuracy: 98.28, accuracySd: 0.1 },
              },
            },
            {
              id: "c1",
              label: "C1: RGB + Swin-B (off the shelf)",
              metrics: {
                ubi: { accuracy: 82.7, accuracySd: 0.3 },
                ucf: { accuracy: 73.07, accuracySd: 0.23 },
                rlvs: { accuracy: 95.62, accuracySd: 0.15 },
              },
            },
          ],
        },
        caption:
          "The C1–C5 ladder, measured against the off-the-shelf baseline. C2 and C3 each change one thing, so their deltas are the two components' individual contributions; C4's delta is smaller than their sum. The gap between C4 and C5 is the adversarial training, and on two datasets it is inside the whiskers.",
      },
      pdfPage: 16,
    },

    {
      id: "adversarial",
      title: "Tested against attacks it was never trained to resist",
      tagline: "T-GAP, PGD and FGSM",
      highlight: {
        label: "Attack success rate",
        value: "4.0 – 8.3%",
        note: "across three attacks and three datasets",
      },
      note: [
        "Adversarial robustness claims are easy to make and easy to make meaninglessly, because a model trained against one attack will naturally resist that attack. This paper avoids the trap by testing against two it never saw.",
        "T-GAP, the paper's own attack, perturbs the temporal gradient channel under an ℓ∞ budget of ε ≈ 13/255 — which the paper correctly notes is high, against typical values of 2/255 and 8/255. Training alternates clean and perturbed TG-RGB+ inputs, with a cosine-similarity loss pulling the two embeddings together.",
        "The result on its own attack is good: 4.5% attack success on UBI-Fights, 4.0% on RLVS, 7.5% on UCF-Crime. But that is the expected outcome and proves little on its own. The number that matters is Table 7, which throws PGD and FGSM at the same model — classic gradient attacks that know nothing about temporal structure.",
        "They do barely better. PGD reaches 5.0% on UBI-Fights against T-GAP's 4.5%, and 8.2% on UCF-Crime against 7.5%. FGSM lands within a tenth of a point of PGD everywhere. The margin in T-GAP's favour is real and small, which is exactly the shape you want: the model has learned something general about resisting perturbation, not merely memorised one attack's signature.",
        "There is a second robustness test, and it is the one closer to a real deployment problem. Table 8 degrades the raw RGB to simulate low light before the temporal gradient is computed, so the motion cue is derived from noisy input rather than clean. AUC falls by 4.00 points on UBI-Fights, 2.00 on RLVS and 0.60 on UCF-Crime. Small drops, and the argument for why — gradient features are less sensitive to illumination than appearance features — is coherent.",
        "The paper's own limitations note the gap honestly: T-GAP perturbs only the gradient channel, and joint perturbation of RGB and gradient together 'could expose residual vulnerabilities'. That has not been tested.",
      ],
      takeaways: [
        "Tested against PGD and FGSM, neither of which the model was trained on. Both do roughly as badly as T-GAP.",
        "ε ≈ 13/255 is a high perturbation budget, well above the 2/255 and 8/255 usually reported.",
        "Low-light degradation costs 0.6 to 4.0 AUC points — the motion channel survives poor illumination.",
        "Only the gradient channel is attacked. Joint RGB-and-gradient perturbation is untested and the paper says so.",
      ],
      visual: {
        kind: "model-lineup",
        options: {
          hue: 230,
          mode: "outcome",
          metricLabel: "Accuracy under attack",
          datasetLabel: "Dataset",
          baselineId: "tgap",
          // T7, p15. Accuracy under attack, with the attack success rate in each
          // lane's label. T-GAP is the baseline because it is the attack the
          // model was trained against -- the question is how close the two
          // unseen attacks get to it.
          datasets: [
            {
              id: "ucf",
              label: "UCF-Crime",
              title: "the only dataset where the attacks separate",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "ubi",
              label: "UBI-Fights",
              title: "clean accuracy 92.47%",
              floor: 50,
              floorLabel: "chance",
            },
            {
              id: "rlvs",
              label: "RLVS",
              title: "clean accuracy 95.11%",
              floor: 50,
              floorLabel: "chance",
            },
          ],
          models: [
            {
              id: "tgap",
              label: "T-GAP (trained against, ASR 4.0-7.5%)",
              metrics: {
                ubi: { accuracy: 91.91 },
                ucf: { accuracy: 75.48 },
                rlvs: { accuracy: 94.49 },
              },
            },
            {
              id: "pgd",
              label: "PGD (unseen, ASR 4.8-8.2%)",
              metrics: {
                ubi: { accuracy: 91.6 },
                ucf: { accuracy: 71.99 },
                rlvs: { accuracy: 94.0 },
              },
            },
            {
              id: "fgsm",
              label: "FGSM (unseen, ASR 4.9-8.3%)",
              metrics: {
                ubi: { accuracy: 91.5 },
                ucf: { accuracy: 71.79 },
                rlvs: { accuracy: 93.92 },
              },
            },
          ],
        },
        caption:
          "T7, measured against the attack the model was trained on. On UBI-Fights and RLVS the three lanes are within half a point of each other — the two unseen attacks do no real damage. UCF-Crime is where the trained-against advantage shows, at 3.5 points.",
      },
      pdfPage: 15,
    },

    {
      id: "realtime",
      title: "Fourteen seconds per clip, described as real-time seventeen times",
      tagline: "T15",
      highlight: {
        label: "Total pipeline",
        value: "13,991 ms/clip",
        note: "for 32 frames — about 2.3 FPS",
      },
      note: [
        "This paper measures its own cost more carefully than anything else in the library. Table 14 gives FLOPs, parameters and memory against four other video transformers. Table 11 costs the input fusion against its alternative. Table 15 breaks the pipeline into components with GFLOPs, inference time and energy for each. Nothing is waved through.",
        "And Table 15 says the swin-3DART forward pass takes 13,932.68 ms per clip. The TG-RGB+ fusion adds 58.53 ms. The total is 13,991.21 ms — roughly fourteen seconds to process a 32-frame clip, or about 2.3 frames per second.",
        "The word real-time appears seventeen times in the paper. The abstract offers the model as suitable for 'deployment in real-time surveillance or edge computing scenarios'. §4.6 states that 'the efficiency gains from 3DART enable real-time, on-device inference'. The conclusion repeats it. None of those sentences is reconciled with the table two rows below them.",
        "What happened is visible in how the efficiency argument is constructed: it is made entirely in FLOPs and memory. Against Swin-B, 3DART cuts FLOPs by 11.9% and memory by 12.0%, and both figures check out exactly. Those are real improvements to a real bottleneck. But a 12% reduction in the cost of an operation that takes fourteen seconds leaves an operation that takes twelve seconds, and the paper never converts its relative saving into an absolute claim about time.",
        "The 13.9-second figure is itself odd enough to flag: 282.79 GFLOPs in 13.9 seconds is about 20 GFLOP/s, far below what the TPU platform named in §4.1.2 would deliver. Whether it reflects an unoptimised implementation, execution on a CPU, or per-clip overhead is not recoverable from the paper. It is the only wall-clock number given, and it is the paper's own.",
        "The same tension runs through the edge-deployment claim. The model needs 4.4 GB of inference memory and the only platform named is a Kaggle TPU with 330 GB. To the authors' credit, the limitations section concedes that the backbone 'remains more computationally demanding than lightweight CNNs, which could hinder deployment on highly constrained devices' — which is the accurate statement, and it contradicts the abstract.",
      ],
      takeaways: [
        "13,991 ms per 32-frame clip, measured and printed by the paper. Real-time at 30 fps needs roughly thirteen times faster.",
        "The efficiency case is argued in FLOPs and memory, where it is correct, and never converted into seconds.",
        "−11.9% off an operation this slow is still an operation this slow.",
        "The limitations section says the accurate thing. The abstract, §4.6 and the conclusion do not.",
      ],
      visual: {
        kind: "throughput-budget",
        options: {
          hue: 230,
          budgetSeconds: 1,
          frameRates: [1, 2, 5, 30],
          // T15, p20. Per-frame costs are the table's per-clip figures divided by
          // the 32-frame clip length T11 and T15 both use: 13932.68/32 = 435.4 ms
          // for the backbone, and 58.53/32 = 1.829 ms for the fusion -- which is
          // exactly the per-frame time T11 prints, so the division checks out.
          stages: [
            {
              id: "backbone",
              label: "swin-3DART forward pass",
              perFrame: 0.43540,
              countedInClaim: true,
              note: "13,932.68 ms per 32-frame clip, 282.79 GFLOPs — the figure the FLOPs argument is about",
            },
            {
              id: "tgrgb",
              label: "TG-RGB+ fusion",
              perFrame: 0.001829,
              countedInClaim: false,
              note: "58.53 ms per clip, 0.11 GFLOPs — the paper calls this under 0.04% of the total, and it is right",
            },
          ],
          copy: {
            readout: "Compute per second of video",
            scopeLabel: "Counting",
            rateLabel: "Input frame rate",
            chips: { claimed: "backbone only", full: "whole pipeline" },
            lines: {
              claimed:
                "The stage the efficiency argument is about: 282.79 GFLOPs against Swin-B's 321, an 11.9% saving. In wall-clock terms it is 435 ms for a single frame.",
              full: "With the input fusion added. The fusion really is negligible — and adding it changes nothing, because the backbone alone is already far over budget.",
            },
          },
        },
        caption:
          "Each solid block is a second of compute owed for one second of video; the outline is the second available. Drop the input rate to 2 fps and the row fits. At 30 fps it needs about thirteen seconds of compute for every second of footage.",
      },
      pdfPage: 20,
    },
  ],
};
